### ISSUE TITLE
Add a @recentchanges+ command to allow users to specify their own 'wiki code'

### ISSUE THREAD

**Issue by maffblaster** [benapetr/wikimedia-bot#62]
Hi,

I was talking to Matthew R. Bowker in the IRC channel trying to figure out what needed to happen in order to support my use case for wm-bot, and I think I have it figured.

mw-bot should accept a custom wiki code so that end users can add the bot's recent change tracking ability to a wiki that's not specified in the 'wiki code' database. This new option would operate almost exactly like the `@rss+ `command. Syntax would be: 

`syntax: @recentchanges+ <name> <url>`

Where` <name>` is the name of the new wiki (it will warn if a wiki code of the same name already exists in the bot's instance of the wiki code database). Admins can force an overwrite for wiki code entries of the same time. Unprivileged users will just get an error that this name is already used.

`<url>` will be the URL for the wiki pages. This is described in the wiki code database already.

Secondarily, it would be great to add the actual Gentoo Wiki to the list of wiki codes present in the repository's configuration/linkie file (if that's the correct file to modify in order to add a new recentchanges site).

Let me know if this is a possibility or if I this feature is already available.

Kind regards

**Comment by Matthewrbowker** [comment]
@benapetr This is your domain.  

A few thoughts: The wikimedia foundation provides a RCStream service for recent changes on a wiki.  It also provides an IRC feed that gives the same information.  As far as I am aware, neither of those are available out of the box within Mediawiki.  So the first major question would be: how do we get a reliable feed for changes?  RSS might be an option, we would just need to be able to parse it.  

That being said, this change would be very beneficial to wm-bot, especially for third parties that don't want to build their own wiki recent changes bot.

**Comment by maffblaster** [comment]
It's been many years and I'm still waiting for a response. I'll move on to something else, as it seems this project, although has some activity on the commit log, seems to have not cut a release for a few years. Only one release total.

Please let me know if the project starts regular releases and/or adds the functionality that was requested above. You can find me in #gentoo-wiki on the Libera network. Thank you!

**Comment by maffblaster** [comment]
Closing as not planed per discussion in the #gentoo-wiki channel on Librechat IRC.
